[platformio]
default_envs = esp32dev
src_dir = src
test_dir = test

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.2
    olikraus/U8g2 @ ^2.35.9
    bblanchon/ArduinoJson @ ^7.0.4
build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DCONFIG_NIMBLE_CPP_LOG_LEVEL=1

[env:native]
platform = native
test_framework = unity
test_build_src = false
build_flags =
    -std=c++11
    -DNATIVE_UNIT_TEST
    -Isrc
